//This file should be autogenerated mostly
import IPokeClient from "./IPokeClient";
import { Pokemon, PokemonConverter, PokemonRoute } from "./generated/resources/Pokemon"
import * as Move from "./generated/resources/Move";


class PokeClient implements IPokeClient
{
    public constructor(){
    }

    Login(): void {
        throw new Error("Method not implemented.");
    }
    
    Register(): void {
        throw new Error("Method not implemented.");
    }

    getPokemon(): Pokemon {
        return new Pokemon();
    }
}