//This file should be autogenerated mostly
import IPokeClient from "./IPokeClient";

class PokeClient implements IPokeClient
{
    public constructor(){
    }

    Login(): void {
        throw new Error("Method not implemented.");
    }
    
    Register(): void {
        throw new Error("Method not implemented.");
    }
}